import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/db/raw';
import { seedJobs,canonicalUrl } from '@/lib/jobs';
export const dynamic='force-dynamic';
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
async function identity(){return (await getChatGPTUser())?.userId;}
export async function GET(){const owner=await identity();if(!owner)return json({error:'Bitte melde dich an, um deine Sammlung zu laden.'},401);try{const db=database();const [custom,states]=await Promise.all([db.prepare('SELECT id,url,title,company,location,source,employment,salary,added_at AS addedAt,kind FROM jobs WHERE owner = ? ORDER BY added_at DESC').bind(owner).all(),db.prepare('SELECT job_id,seen,favorite,dismissed FROM job_state WHERE owner = ?').bind(owner).all()]);const state=new Map(states.results.map((x:any)=>[x.job_id,x]));const all=[...custom.results,...seedJobs].map((j:any)=>({...j,seen:!!state.get(j.id)?.seen,favorite:!!state.get(j.id)?.favorite,dismissed:!!state.get(j.id)?.dismissed}));return json({jobs:all});}catch{return json({error:'Deine Sammlung konnte nicht geladen werden. Bitte erneut versuchen.'},503);}}
function validWrite(req:Request){const origin=req.headers.get('origin');return !origin||origin===new URL(req.url).origin;}
export async function POST(req:Request){if(!validWrite(req))return json({error:'Ungültige Anfrage.'},403);const owner=await identity();if(!owner)return json({error:'Bitte melde dich zuerst an.'},401);let body:any;try{body=await req.json();}catch{return json({error:'Ungültige Eingabe.'},400);}try{if(typeof body?.url!=='string'||body.url.length>3000||typeof body.title!=='string'||!body.title.trim()||body.title.length>240) return json({error:'Bitte Jobtitel und gültigen Link angeben (Titel maximal 240 Zeichen).'},400);const {url,source}=canonicalUrl(body.url);for(const key of ['company','location'])if(body[key]!=null&&(typeof body[key]!=='string'||body[key].length>200))return json({error:'Firma und Ort dürfen höchstens 200 Zeichen enthalten.'},400);const db=database();const known=seedJobs.find(j=>canonicalUrl(j.url).url===url);const existing=known??await db.prepare('SELECT id FROM jobs WHERE owner = ? AND url = ?').bind(owner,url).first();const id=existing?.id as string||crypto.randomUUID();const statements=[];if(!existing)statements.push(db.prepare('INSERT INTO jobs (id,owner,url,title,company,location,source,employment,salary,added_at,kind) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,owner,url,body.title.trim(),body.company?.trim()||'Unternehmen nicht angegeben',body.location?.trim()||'Ort nicht angegeben',source,'','',new Date().toISOString(),'selbst hinzugefügt'));statements.push(db.prepare('INSERT INTO job_state (owner,job_id,seen,favorite) VALUES (?,?,0,1) ON CONFLICT(owner,job_id) DO UPDATE SET favorite=1,dismissed=0').bind(owner,id));await db.batch(statements);return json({id,saved:true,existing:!!existing});}catch(e){if(e instanceof TypeError||e instanceof Error&&/Link|Unterstützt/.test(e.message))return json({error:e.message},400);return json({error:'Der Job konnte nicht gespeichert werden. Bitte erneut versuchen.'},503);}}
export async function PATCH(req:Request){if(!validWrite(req))return json({error:'Ungültige Anfrage.'},403);const owner=await identity();if(!owner)return json({error:'Bitte melde dich zuerst an.'},401);let body:any;try{body=await req.json();}catch{return json({error:'Ungültige Eingabe.'},400);}if(typeof body?.id!=='string'||!['seen','favorite','dismissed'].includes(body.field)||typeof body.value!=='boolean')return json({error:'Ungültige Änderung.'},400);try{const db=database();if(!seedJobs.some(j=>j.id===body.id)&&!await db.prepare('SELECT id FROM jobs WHERE id = ? AND owner = ?').bind(body.id,owner).first())return json({error:'Stelle nicht gefunden.'},404);const seen=body.field==='seen'?+body.value:0,favorite=body.field==='favorite'?+body.value:0,dismissed=body.field==='dismissed'?+body.value:0;await db.prepare(`INSERT INTO job_state (owner,job_id,seen,favorite,dismissed) VALUES (?,?,?,?,?) ON CONFLICT(owner,job_id) DO UPDATE SET ${body.field}=excluded.${body.field}`).bind(owner,body.id,seen,favorite,dismissed).run();return json({saved:true});}catch{return json({error:'Änderung konnte nicht gespeichert werden. Bitte erneut versuchen.'},503);}}
